config/routes.rb
Rails.application.routes.draw do
  resources 'feed_channels', only: [:index, :show]

  root to: "feed_channels#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :items

  validates_presence_of :title, :author, :description

  def to_s
    "#{title} - #{subtitle}, #{author}"
  end

  def publish
    # publish to S3
    body = ChannelsController.render "show.rss", layout: false, assigns: {ch: self}
    obj = S3_BUCKET.object(published_filename)
    obj.put(body: body)
  end

  def published_filename
    "#{id}.rss"
  end

  def published_url
    "https://#{ENV['CLOUDFRONT_DOMAIN']}/#{published_filename}"
  end

end

app/models/feed_channel.rb
class FeedChannel < ApplicationRecord
  self.table_name = 'channels'

  has_many :items, foreign_key: 'channel_id'

  validates_presence_of :title, :author, :description

  def to_s
    "#{title} - #{subtitle}, #{author}"
  end

  def publish
    # publish to S3
    body = FeedChannelsController.render "show.rss", layout: false, assigns: {ch: self}
    obj = S3_BUCKET.object(published_filename)
    obj.put(body: body)
  end

  def published_filename
    "#{id}.rss"
  end

  def published_url
    "https://#{ENV['CLOUDFRONT_DOMAIN']}/#{published_filename}"
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :feed_channel, foreign_key: 'channel_id'

  validates_presence_of :title, :author, :url, :pub_date

  before_create {|item|
    item.uuid = SecureRandom.hex(32)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/feed_channels_controller.rb
class FeedChannelsController < ApplicationController
  def index
    @channels = FeedChannel.all
  end

  def show
    @ch = FeedChannel.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
  # from http://stackoverflow.com/questions/4136248
  def humanize_time(secs)
    return "" if secs.nil?
    [[60, :s], [60, :m], [24, :h], [1000, :d]].map{ |count, name|
      if secs > 0
        secs, n = secs.divmod(count)
        "#{n.to_i}#{name}"
      end
    }.compact.reverse.join(' ')
  end

  # Fixed version of https://gist.github.com/260184
  def humanize_size(number)
    return nil if number.nil?

    storage_units_format = '%n %u'

    if number.to_i < 1024
      unit = number > 1 ? 'Bytes' : 'Byte'
      return storage_units_format.gsub(/%n/, number.to_i.to_s).gsub(/%u/, unit)
    else
      max_exp  = STORAGE_UNITS.size - 1
      number   = Float(number)
      exponent = (Math.log(number) / Math.log(1024)).to_i # Convert to base 1024
      exponent = max_exp if exponent > max_exp # we need this to avoid overflow for the highest unit
      number  /= 1024 ** exponent

      unit = STORAGE_UNITS[exponent]
      return storage_units_format.gsub(/%n/, number.to_i.to_s).gsub(/%u/, unit)
    end
  end

end

app/helpers/feed_channels_helper.rb
module FeedChannelsHelper
  # from http://stackoverflow.com/questions/4136248
  def humanize_time(secs)
    return "" if secs.nil?
    [[60, :s], [60, :m], [24, :h], [1000, :d]].map{ |count, name|
      if secs > 0
        secs, n = secs.divmod(count)
        "#{n.to_i}#{name}"
      end
    }.compact.reverse.join(' ')
  end

  # Fixed version of https://gist.github.com/260184
  def humanize_size(number)
    return nil if number.nil?

    number_to_human_size number
  end

end

app/views/feed_channels/index.html.erb
<h1>Channels</h1>
<% @channels.each do |channel| %>
  <p>
    <%= link_to channel, feed_channel_path(channel, format: 'html') %>
    &nbsp;|&nbsp;
    <%= link_to "RSS", feed_channel_path(channel, format: 'rss') %>
  </p>
<% end %>

app/views/feed_channels/show.html.erb
<!DOCTYPE html>
<html lang="<%= @ch.language %>">
<head>
  <meta charset="utf-8"/>
  <title><%= @ch.title %></title>
  <meta name="generator" content="Podcastgen"/>
  <meta name="keywords" content="<%= @ch.keywords %>"/>
  <% unless @ch.copyright.blank? %>
  <meta name="copyright" content="<%= @ch.copyright %>"/>
  <% end %>
  <link rel="canonical" href="<%= @ch.url %>"/>
  <link rel="alternate" type="application/rss+xml" title="<%= @ch.title %> Podcast Feed" href="<%= @ch.url %>">
</head>

<body id="home">
  <h1><%= @ch.title %></h1>
  <% unless @ch.subtitle.blank? %>
  <h2><%= @ch.subtitle %></h2>
  <% end %>
  
  <% unless @ch.image_url.blank? %>
  <img src="<%= @ch.image_url %>"/>
  <% end %>
  <p><%= @ch.description %></p>

  <h1>Episodes</h1>
  <% @ch.items.each{|item| %>
    <div class="item" id="<%= item.uuid %>">
      <h2><%= item.title %></h2>
    <% unless item.subtitle.blank? %>
      <h3><%= item.subtitle %></h3>
    <% end %>
      <img src="<%= item.image_url %>"/>
      <p>Download: <a href="<%= item.url %>">MP3</a> (<%= humanize_time(item.duration) %>, <%= humanize_size(item.file_size) %>)</p>
      <p>Published <%= item.pub_date.to_formatted_s(:rfc822) %></p>
    <% unless item.keywords.blank? %>
      <p><%= item.keywords %></p>
    <% end %>
    </div>
  <% } %>
</body>
</html>

app/views/feed_channels/show.rss.erb
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file generated by Podcastgen -->
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">
  <channel>
    <title><%= @ch.title %></title>
    <link><%= @ch.url %></link>
    <description><%= @ch.description %></description>
    <itunes:summary><%= @ch.description %></itunes:summary>
    <% unless @ch.language.blank? %>
    <language><%= @ch.language %></language>
    <% end %>
    <% unless @ch.copyright.blank? %>
    <copyright><%= @ch.copyright %></copyright>
    <% end %>
    <% unless @ch.subtitle.blank? %>
    <itunes:subtitle><%= @ch.subtitle %></itunes:subtitle>
    <% end %>
    <% unless @ch.author.blank? %>
    <itunes:author><%= @ch.author %></itunes:author>
    <% end %>
    <% unless @ch.owner_name.nil? %>
    <itunes:owner>
      <itunes:name><%= @ch.owner_name %></itunes:name>
      <itunes:email><%= @ch.owner_email %></itunes:email>
    </itunes:owner>
    <% end %>
    <% unless @ch.image_url.blank? %>
    <itunes:image href="<%= @ch.image_url %>" />
    <% end %>
    <% unless @ch.categories.blank? %>
    <itunes:category text="<%= @ch.categories %>" />
    <% end %>
    <itunes:explicit><%= @ch.explicit ? 'Yes' : 'No' %></itunes:explicit>
    <generator>Podcastgen</generator>
    <% unless @ch.keywords.blank? %>
    <itunes:keywords><%= @ch.keywords %></itunes:keywords>
  <% end %>
  <% @ch.items.each{|item| %>
    <item>
      <title><%= item.title %></title>
      <itunes:author><%= item.author %></itunes:author>
      <itunes:subtitle><%= item.subtitle %></itunes:subtitle>
      <itunes:summary><%= item.summary %></itunes:summary>
      <itunes:image href="<%= item.image_url %>" />
      <enclosure url="<%= item.url %>" length="<%= item.file_size %>" type="audio/mp3" />
      <link><%= item.url %></link>
      <guid isPermaLink="false"><%= item.uuid %></guid>
      <pubDate><%= item.pub_date.rfc2822 %></pubDate>
      <itunes:duration><%= item.duration %></itunes:duration>
    <% unless item.keywords.blank? %>
      <itunes:keywords><%= item.keywords %></itunes:keywords>
    <% end %>
    </item>
  <% } %>
  </channel>
</rss>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podcastgen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>